---
default_language_version:
  python: python3.12
fail_fast: false
repos:
  - repo: https://github.com/ambv/black
    rev: 25.1.0
    hooks:
      - id: black

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.11.2
    hooks:
      - id: ruff
        types_or: [python]
      - id: ruff-format
