FROM postgres:17

USER root

RUN apt-get update &&  \ 
    apt-get -y install postgresql-17-cron && \ 
    apt-get clean \ 
    && rm -rf /var/lib/apt/lists/*

COPY ./init_pg_cron.sh /docker-entrypoint-initdb.d/
RUN chmod +x /docker-entrypoint-initdb.d/init_pg_cron.sh

USER postgres

CMD ["postgres", "-c", "shared_preload_libraries=pg_cron"]