blank_issues_enabled: false
contact_links:
  - name: Security Contact
    # TODO: add real feedback email
    about: Please report security vulnerabilities to security@genai.works
  # - name: Question or Problem
  #   about: Ask a question or ask about a problem in GitHub Discussions.
  #   url: #TODO: discussions page or link to external messenger
  # - name: Feature Request
  #   about: To suggest an idea or ask about a feature, please start with a question saying what you would like to achieve. There might be a way to do it already.
  #   url: #TODO: discussions page or link to external messenger
  # - name: Share your agent/flow
  #   about: Show what you built with GenAI or to be used with GenAI.
  #   url: #TODO: link to
