"""Initial migrations

Revision ID: bdf04422c056
Revises: 
Create Date: 2025-07-08 11:59:55.097357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bdf04422c056'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.create_table('teams',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_teams_id'), 'teams', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('a2acards',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('alias', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('server_url', sa.String(), nullable=False),
    sa.Column('card_content', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('creator_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('creator_id', 'server_url', name='uq_a2a_card_server_url')
    )
    op.create_index(op.f('ix_a2acards_creator_id'), 'a2acards', ['creator_id'], unique=False)
    op.create_index(op.f('ix_a2acards_id'), 'a2acards', ['id'], unique=False)
    op.create_table('agents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('alias', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('jwt', sa.String(), nullable=False),
    sa.Column('creator_id', sa.UUID(), nullable=True),
    sa.Column('input_parameters', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_invoked_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alias'),
    sa.UniqueConstraint('jwt')
    )
    op.create_index(op.f('ix_agents_creator_id'), 'agents', ['creator_id'], unique=False)
    op.create_index(op.f('ix_agents_id'), 'agents', ['id'], unique=False)
    op.create_table('agentworkflows',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('alias', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('flow', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('creator_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alias')
    )
    op.create_index(op.f('ix_agentworkflows_creator_id'), 'agentworkflows', ['creator_id'], unique=False)
    op.create_index(op.f('ix_agentworkflows_id'), 'agentworkflows', ['id'], unique=False)
    op.create_table('chatconversations',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('creator_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_index(op.f('ix_chatconversations_creator_id'), 'chatconversations', ['creator_id'], unique=False)
    op.create_index(op.f('ix_chatconversations_session_id'), 'chatconversations', ['session_id'], unique=False)
    op.create_table('files',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('request_id', sa.UUID(), nullable=True),
    sa.Column('creator_id', sa.UUID(), nullable=True),
    sa.Column('mimetype', sa.String(), nullable=False),
    sa.Column('original_name', sa.String(), nullable=False),
    sa.Column('internal_name', sa.String(), nullable=False),
    sa.Column('internal_id', sa.UUID(), nullable=False),
    sa.Column('from_agent', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_files_creator_id'), 'files', ['creator_id'], unique=False)
    op.create_index(op.f('ix_files_id'), 'files', ['id'], unique=False)
    op.create_index(op.f('ix_files_internal_id'), 'files', ['internal_id'], unique=False)
    op.create_index(op.f('ix_files_request_id'), 'files', ['request_id'], unique=False)
    op.create_index(op.f('ix_files_session_id'), 'files', ['session_id'], unique=False)
    op.create_table('logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('request_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.String(), nullable=True),
    sa.Column('creator_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('log_level', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_logs_agent_id'), 'logs', ['agent_id'], unique=False)
    op.create_index(op.f('ix_logs_creator_id'), 'logs', ['creator_id'], unique=False)
    op.create_index(op.f('ix_logs_id'), 'logs', ['id'], unique=False)
    op.create_index(op.f('ix_logs_request_id'), 'logs', ['request_id'], unique=False)
    op.create_index(op.f('ix_logs_session_id'), 'logs', ['session_id'], unique=False)
    op.create_table('mcpservers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('server_url', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('creator_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('creator_id', 'server_url', name='uq_mcp_server_url')
    )
    op.create_index(op.f('ix_mcpservers_creator_id'), 'mcpservers', ['creator_id'], unique=False)
    op.create_index(op.f('ix_mcpservers_id'), 'mcpservers', ['id'], unique=False)
    op.create_table('modelproviders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('api_key', sa.String(), nullable=True),
    sa.Column('provider_metadata', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('creator_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('creator_id', 'name', name='uq_user_provider_name')
    )
    op.create_index(op.f('ix_modelproviders_creator_id'), 'modelproviders', ['creator_id'], unique=False)
    op.create_index(op.f('ix_modelproviders_id'), 'modelproviders', ['id'], unique=False)
    op.create_table('user_project_associations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_project_associations_id'), 'user_project_associations', ['id'], unique=False)
    op.create_index(op.f('ix_user_project_associations_project_id'), 'user_project_associations', ['project_id'], unique=False)
    op.create_index(op.f('ix_user_project_associations_user_id'), 'user_project_associations', ['user_id'], unique=False)
    op.create_table('user_team_associations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_team_associations_id'), 'user_team_associations', ['id'], unique=False)
    op.create_index(op.f('ix_user_team_associations_team_id'), 'user_team_associations', ['team_id'], unique=False)
    op.create_index(op.f('ix_user_team_associations_user_id'), 'user_team_associations', ['user_id'], unique=False)
    op.create_table('userprofiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_userprofiles_id'), 'userprofiles', ['id'], unique=False)
    op.create_index(op.f('ix_userprofiles_user_id'), 'userprofiles', ['user_id'], unique=False)
    op.create_table('agent_project_associations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_project_associations_agent_id'), 'agent_project_associations', ['agent_id'], unique=False)
    op.create_index(op.f('ix_agent_project_associations_id'), 'agent_project_associations', ['id'], unique=False)
    op.create_index(op.f('ix_agent_project_associations_project_id'), 'agent_project_associations', ['project_id'], unique=False)
    op.create_table('agentflow_project_associations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('flow_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['flow_id'], ['agentworkflows.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agentflow_project_associations_flow_id'), 'agentflow_project_associations', ['flow_id'], unique=False)
    op.create_index(op.f('ix_agentflow_project_associations_id'), 'agentflow_project_associations', ['id'], unique=False)
    op.create_index(op.f('ix_agentflow_project_associations_project_id'), 'agentflow_project_associations', ['project_id'], unique=False)
    op.create_table('chatmessages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('request_id', sa.Uuid(), nullable=True),
    sa.Column('sender_type', sa.Enum('user', 'master_agent', name='sendertype'), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('extra_metadata', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['chatconversations.session_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chatmessages_conversation_id'), 'chatmessages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_chatmessages_id'), 'chatmessages', ['id'], unique=False)
    op.create_table('mcptools',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('inputSchema', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('annotations', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('alias', sa.String(), nullable=True),
    sa.Column('mcp_server_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['mcp_server_id'], ['mcpservers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mcptools_id'), 'mcptools', ['id'], unique=False)
    op.create_index(op.f('ix_mcptools_mcp_server_id'), 'mcptools', ['mcp_server_id'], unique=False)
    op.create_table('modelconfigs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('provider_id', sa.UUID(), nullable=True),
    sa.Column('system_prompt', sa.String(), nullable=False),
    sa.Column('user_prompt', sa.String(), nullable=True),
    sa.Column('max_last_messages', sa.Integer(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('credentials', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('creator_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provider_id'], ['modelproviders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('creator_id', 'name', name='uq_user_config_name')
    )
    op.create_index(op.f('ix_modelconfigs_creator_id'), 'modelconfigs', ['creator_id'], unique=False)
    op.create_index(op.f('ix_modelconfigs_id'), 'modelconfigs', ['id'], unique=False)
    op.create_index(op.f('ix_modelconfigs_model'), 'modelconfigs', ['model'], unique=False)
    op.create_index(op.f('ix_modelconfigs_provider_id'), 'modelconfigs', ['provider_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_modelconfigs_provider_id'), table_name='modelconfigs')
    op.drop_index(op.f('ix_modelconfigs_model'), table_name='modelconfigs')
    op.drop_index(op.f('ix_modelconfigs_id'), table_name='modelconfigs')
    op.drop_index(op.f('ix_modelconfigs_creator_id'), table_name='modelconfigs')
    op.drop_table('modelconfigs')
    op.drop_index(op.f('ix_mcptools_mcp_server_id'), table_name='mcptools')
    op.drop_index(op.f('ix_mcptools_id'), table_name='mcptools')
    op.drop_table('mcptools')
    op.drop_index(op.f('ix_chatmessages_id'), table_name='chatmessages')
    op.drop_index(op.f('ix_chatmessages_conversation_id'), table_name='chatmessages')
    op.drop_table('chatmessages')
    op.drop_index(op.f('ix_agentflow_project_associations_project_id'), table_name='agentflow_project_associations')
    op.drop_index(op.f('ix_agentflow_project_associations_id'), table_name='agentflow_project_associations')
    op.drop_index(op.f('ix_agentflow_project_associations_flow_id'), table_name='agentflow_project_associations')
    op.drop_table('agentflow_project_associations')
    op.drop_index(op.f('ix_agent_project_associations_project_id'), table_name='agent_project_associations')
    op.drop_index(op.f('ix_agent_project_associations_id'), table_name='agent_project_associations')
    op.drop_index(op.f('ix_agent_project_associations_agent_id'), table_name='agent_project_associations')
    op.drop_table('agent_project_associations')
    op.drop_index(op.f('ix_userprofiles_user_id'), table_name='userprofiles')
    op.drop_index(op.f('ix_userprofiles_id'), table_name='userprofiles')
    op.drop_table('userprofiles')
    op.drop_index(op.f('ix_user_team_associations_user_id'), table_name='user_team_associations')
    op.drop_index(op.f('ix_user_team_associations_team_id'), table_name='user_team_associations')
    op.drop_index(op.f('ix_user_team_associations_id'), table_name='user_team_associations')
    op.drop_table('user_team_associations')
    op.drop_index(op.f('ix_user_project_associations_user_id'), table_name='user_project_associations')
    op.drop_index(op.f('ix_user_project_associations_project_id'), table_name='user_project_associations')
    op.drop_index(op.f('ix_user_project_associations_id'), table_name='user_project_associations')
    op.drop_table('user_project_associations')
    op.drop_index(op.f('ix_modelproviders_id'), table_name='modelproviders')
    op.drop_index(op.f('ix_modelproviders_creator_id'), table_name='modelproviders')
    op.drop_table('modelproviders')
    op.drop_index(op.f('ix_mcpservers_id'), table_name='mcpservers')
    op.drop_index(op.f('ix_mcpservers_creator_id'), table_name='mcpservers')
    op.drop_table('mcpservers')
    op.drop_index(op.f('ix_logs_session_id'), table_name='logs')
    op.drop_index(op.f('ix_logs_request_id'), table_name='logs')
    op.drop_index(op.f('ix_logs_id'), table_name='logs')
    op.drop_index(op.f('ix_logs_creator_id'), table_name='logs')
    op.drop_index(op.f('ix_logs_agent_id'), table_name='logs')
    op.drop_table('logs')
    op.drop_index(op.f('ix_files_session_id'), table_name='files')
    op.drop_index(op.f('ix_files_request_id'), table_name='files')
    op.drop_index(op.f('ix_files_internal_id'), table_name='files')
    op.drop_index(op.f('ix_files_id'), table_name='files')
    op.drop_index(op.f('ix_files_creator_id'), table_name='files')
    op.drop_table('files')
    op.drop_index(op.f('ix_chatconversations_session_id'), table_name='chatconversations')
    op.drop_index(op.f('ix_chatconversations_creator_id'), table_name='chatconversations')
    op.drop_table('chatconversations')
    op.drop_index(op.f('ix_agentworkflows_id'), table_name='agentworkflows')
    op.drop_index(op.f('ix_agentworkflows_creator_id'), table_name='agentworkflows')
    op.drop_table('agentworkflows')
    op.drop_index(op.f('ix_agents_id'), table_name='agents')
    op.drop_index(op.f('ix_agents_creator_id'), table_name='agents')
    op.drop_table('agents')
    op.drop_index(op.f('ix_a2acards_id'), table_name='a2acards')
    op.drop_index(op.f('ix_a2acards_creator_id'), table_name='a2acards')
    op.drop_table('a2acards')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_teams_id'), table_name='teams')
    op.drop_table('teams')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_table('projects')
    # ### end Alembic commands ###
